#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &

for monitor in $(bspc query -M); do
    bspc monitor $monitor -d 1 2 3 4
done

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a rofi focus=on
